#!/bin/sh
# Set environment
export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"

bspc config border_width        5
bspc config window_gap          8
bspc config top_padding         0

bspc config split_ratio                 0.50
bspc config borderless_monocle          false
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true
bspc config history_aware_focus         true

bspc config focused_border_color     "#BD93F9"
bspc config normal_border_color      "#282A36"
bspc config active_border_color      "#8BE9FD"
bspc config presel_feedback_color    "#50FA7B"

bspc monitor --reset-desktops 1 2 3 4 
# Make windows float on specific desktops
bspc subscribe node_manage | while read -r event monitor desktop nodeid ipid; do
	case "$desktop" in
	    2|3|4)
			bspc node "$nodeid" --state floating
			;;
	esac
done &
bspc rule --add Gimp                        desktop='3' follow=off
bspc rule --add Gimp-2.8                    desktop='3' follow=off
bspc rule --add qutebrowser                    desktop='2' follow=off
setxkbmap -option caps:escape -option grp:win_space_toggle us,ara &
# bspwmbar &
sxhkd &
xclip &
#picom &
xrandr -r 60 &
xfce4-power-manager &
feh --bg-fill Downloads/wallpaper &
pipewire &
light -S 0 &
